# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.x'
              includePreviewVersions: true
          # pack one artifact with no version suffix
          - task: CmdLine@2
            inputs:
              script: 'dotnet pack --output $(Build.StagingDirectory)/prod'
          # pack one artifact with WITH suffix
          - task: CmdLine@2
            inputs:
              script: 'dotnet pack --version-suffix $(Build.BuildNumber) --output $(Build.StagingDirectory)/ci'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.StagingDirectory)'
              artifact: 'nuget'
              publishLocation: 'pipeline'
  - stage: DeployDev
    dependsOn: build
    displayName: Deploy Dev
    jobs:
      - deployment: deployDev
        environment: AssemblyInfo-DEV
        displayName: Deploy Nuget
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          runOnce: #rolling, canary are the other strategies that are supported
            deploy:
              steps:
                - task: NuGetToolInstaller@1
                  inputs:
                    versionSpec: '5.x'
                - task: NuGetAuthenticate@0
                  inputs:
                    nuGetServiceConnections: 'Nuget.Org'
                - task: NuGetCommand@2
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Build.ArtifactStagingDirectory)/ci/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/ci/**/*.symbols.nupkg'
                    nuGetFeedType: 'internal'
                    # Publishes to the 'CI' feed
                    publishVstsFeed: '74b36810-12b7-443b-8f7f-0b69063afebd'
                    allowPackageConflicts: true
  - stage: DeployProd
    dependsOn: DeployDev
    displayName: Deploy Prod
    jobs:
      - deployment: deployProd
        environment: AssemblyInfo-PROD
        displayName: Deploy Nuget
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          runOnce: #rolling, canary are the other strategies that are supported
            deploy:
              steps:
                - task: NuGetToolInstaller@1
                  inputs:
                    versionSpec: '5.x'
                - task: NuGetAuthenticate@0
                  inputs:
                    nuGetServiceConnections: 'Nuget.Org'
                - task: NuGetCommand@2
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Build.ArtifactStagingDirectory)/prod/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/prod/**/*.symbols.nupkg'
                    nuGetFeedType: 'external'
                    publishFeedCredentials: 'Nuget.Org'
