# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    includePreviewVersions: true
# pack one artifact with no version suffix
- task: CmdLine@2
  inputs:
    script: 'dotnet pack --output $(Build.StagingDirectory)'
# pack one artifact with WITH suffix
- task: CmdLine@2
  inputs:
    script: 'dotnet pack --version-suffix $(Build.BuildNumber) --output $(Build.StagingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.StagingDirectory)'
    artifact: 'nuget'
    publishLocation: 'pipeline'
